[tool.poetry]
name = "eeg-mindflex"
version = "0.1.0"
description = "Neurofeedback application for the Mindflex"
authors = ["Alexander Bernauer <acopton@gmail.com>", "jovelleu <jovell@gmail.com>"]
readme = "README.md"
packages = [
    { include = "app" }
]

[tool.poetry.scripts]
app = "app.main:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.26.2"
pyserial = "^3.5"
pyqtgraph = "^0.13.0"
pyside6 = "^6.0.0"
rich = "^13.9.4"

[tool.poetry.group.windows.dependencies]
comtypes = "^1.1.12"
pycaw = "^20240210"

[tool.poetry.group.macos.dependencies]

[tool.poetry.group.linux.dependencies]

[tool.poetry.group.dev.dependencies]
mypy = ">=1.0.0"
pytest = ">=8.3.4"
pre-commit = "^3.6.0"
autoflake = "^2.3.1"
pytest-mock = "^3.14.0"
pytest-dependency = "^0.6.0"
ruff = "^0.9.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"
line-length = 110
lint.select = [
    # pycodestyle
    "E",
    # pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # isort
    "I",
]

[tool.mypy]
mypy_path = "app"

[tool.autoflake]
exclude = [
    "app/ui/__init__.py",
    "app/framework/__init__.py",
    "app/data_processing/__init__.py",
    "app/__init__.py",
    "app/system/__init__.py",
    "app/sensor/__init__.py",
]
