[tool.poetry]
name = "eeg-mindflex"
version = "0.1.0"
description = "Neurofeedback application for the Mindflex"
authors = ["Alexander Bernauer <acopton@gmail.com>", "jovelleu <jovell@gmail.com>"]
readme = "README.md"
packages = [
    { include = "app" }
]

[tool.poetry.scripts]
app = "app.main:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.26.2"
pyserial = "^3.5"
pyqtgraph = "^0.13.0"
pyside6 = "^6.0.0"

[tool.poetry.group.windows.dependencies]
comtypes = "^1.1.12"
pycaw = "^20240210"

[tool.poetry.group.macos.dependencies]

[tool.poetry.group.linux.dependencies]

[tool.poetry.group.dev.dependencies]
black = ">=23.0.0"
isort = ">=5.0.0"
mypy = ">=1.0.0"
flake8 = ">=6.0.0"
flake8-pyproject = ">=1.0.0"
pytest = ">=8.3.4"
pre-commit = "^3.6.0"
autoflake = "^2.3.1"
pytest-mock = "^3.14.0"
pytest-dependency = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
line_length = 110
include_trailing_comma = true

[tool.black]
line_length = 110

[tool.flake8]
max-line-length = 111
extend-ignore = "E203"  # Black and flake8 disagree on whitespace before a colon
per-file-ignores = [
    "app/ui/__init__.py:F401",
    "app/framework/__init__.py:F401",
    "app/data_processing/__init__.py:F401",
    "app/__init__.py:F401",
    "app/system/__init__.py:F401",
    "app/sensor/__init__.py:F401",
]

[tool.mypy]
mypy_path = "app"

[tool.autoflake]
exclude = [
    "app/ui/__init__.py",
    "app/framework/__init__.py",
    "app/data_processing/__init__.py",
    "app/__init__.py",
    "app/system/__init__.py",
    "app/sensor/__init__.py",
]
